### ISSUE TITLE
I can't open a new project

### ISSUE THREAD

**Issue by victoireblein** [emlyon/Designing-With-Web#11]
Hello, 
I created a new file for the work we need to submit however when i try to open my project in a new page it always opens the 'html" file I created first to train. What can I do? Do I have to create a new file?

**Comment by MAKIO135** [comment]
Hello Victoire,  
What do you mean by *it always opens the "html" file I created first to train*?  
Is it that when you're clicking on "Show Live", you see your first HTML file? I think this is because your first file is named `index.html`, which is the name for the default file to open. You should rename your first file to something like `training.html` and name your second file `index.html`

If you want to see different pages, you can keep `index.html`for the file to open on https://yourprojectname.glitch.me/ and you can access to others html pages like `training.html` on https://yourprojectname.glitch.me/training.html  
See https://glitch.com/edit/#!/hello-html-links for an example with 2 pages

**Comment by victoireblein** [comment]
Hello,
I thought I could create a new HTML document because I trained on the « index.html » document I created. I was told this morning that I had to do the assignment on my index.html document which I did.
Was it possible to do it another way?
Best regards
Victoire

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MAKIO135** [comment]
The browser will always open the file named `index.html` if you do not specify the path to a HTML file in the address eg:
https://yourprojectname.glitch.me/ vs https://yourprojectname.glitch.me/training.html

You can simply click on your filenames in the sidebar to rename them.

**Comment by victoireblein** [comment]
Hello,

Sorry to bother you again. I’m trying to finish the last assignment, I renamed the project however it always opens the “index.html” file which was the first assignment. Should I name “index.html” the 2nd assignment and rename the first one? Because I can’t visualize it.. But I fear it might impact my 1st assignment and no one will be able to see it. Or should I ask the makers Lab?
Thank you
Victoire
De : Lionel RADISSON <notifications@github.com>
Répondre à : emlyon/Designing-With-Web <reply@reply.github.com>
Date : mercredi 10 octobre 2018 à 16:49
À : emlyon/Designing-With-Web <Designing-With-Web@noreply.github.com>
Cc : BLEIN Victoire <victoire.blein@edu.em-lyon.com>, Author <author@noreply.github.com>
Objet : Re: [emlyon/Designing-With-Web] I can't open a new project (#11)

https://yourprojectname.glitch.me/

**Comment by MAKIO135** [comment]
Simply connect to your account on glitch.com and create a new project.

Le lun. 15 oct. 2018 à 10:50, victoireblein <notifications@github.com> a
écrit :
