### ISSUE TITLE
"Show live" + "Markdow" 

### ISSUE THREAD

**Issue by MelanieRupert** [emlyon/Designing-With-Web#3]
Hi ! 

I don't understand why my app doesn't "live" the same way as "Markdown". 

I wrote this (at the end of "Readme") : 
![markdown](https://user-images.githubusercontent.com/43700756/46246102-d5bc6700-c3f8-11e8-92cb-6c0d5b9a3663.JPG)

And then, when I click on "Markdown", it is working : 

![image](https://user-images.githubusercontent.com/43700756/46246114-013f5180-c3f9-11e8-8592-6b50374aa6de.png)

But when i'm looking at "showlive", it's not working at all : 

![image](https://user-images.githubusercontent.com/43700756/46246129-26cc5b00-c3f9-11e8-8661-4a9506733ea1.png)

How can you explain that ? What can i do ? 

Thanks ! 

Mélanie.

**Comment by MAKIO135** [comment]
It looks like you've pasted the content of your `readme.md` inside of your ìndex.html`, is it the case?
If so, the result on the *live view* is expected since a browser is not intended to display markdown. What is displayed on glitch as your `readme.md` is the result of generated HTML from the markdown you wrote.
