### ISSUE TITLE
Skeleton's grid are not responsive

### ISSUE THREAD

**Issue by JosephGignoux** [emlyon/Designing-With-Web#6]
Hello !! :)

I noticed that the skeleton's column are not responsive... So on my web page it's ok I have my two columns side to side but when I open the page on my mobile, everything come in one column. 
Is it normal ?

Thanks !

**Comment by MAKIO135** [comment]
Well **that's the principle of responsive design**: with larger screens, your columns are wider and side by side, while on smaller devices, columns contract themselves, and instead of becoming too small they turn to one column

See issue #5 and BrightSpace news posted yesterday:
!()[https://raw.githubusercontent.com/emlyon/Designing-With-Web/master/columns.gif]
